from ai.provider_interface import AIProvider


class RuleBasedProvider(AIProvider):
    """Default provider. Zero external dependency, zero cost, never fails.
    The reasoning/factors/risk_factors were already generated by the agent's
    deterministic templater, so this provider just passes them through."""

    name = "rule_based"

    def enrich(self, *, event, market_type, signals, rule_based, regime, memory_hint) -> dict:
        return {
            "reasoning": rule_based["reasoning"],
            "factors": rule_based["factors"],
            "risk_factors": rule_based["risk_factors"],
            "provider_used": "rule_based",
        }
