import { useState } from "react";
import { useSystem } from "../state/SystemProvider";
import { Panel, Badge, Empty, PageHeader, DataTable, StatRow, StatTile } from "../components/ui";
import type { Column } from "../components/ui";
import type { DecisionRow } from "../types";
import { PipelineFlow } from "../components/PipelineFlow";
import { fmtCurrency, fmtPct, fmtTime, pnlTone } from "../utils/format";
import { T, ASSET_NAME, AGENT_LABEL, actionInfo, verdictInfo, regimeInfo, strategyLabel, humanize } from "../utils/vocab";

type Filter = "ALL" | "ACTED" | "BLOCKED";

export default function Decisions() {
  const { latest, decisions, focus, setPinnedAsset, pinnedAsset } = useSystem();
  const [filter, setFilter] = useState<Filter>("ALL");
  const [openId, setOpenId] = useState<number | null>(null);

  const rows = decisions.filter((d) => {
    if (filter === "ACTED") return d.executed;
    if (filter === "BLOCKED") return d.risk_verdict !== "APPROVE";
    return true;
  });

  const columns: Column<DecisionRow>[] = [
    { key: "step", header: "Step", width: "58px", align: "right", sortable: true, sortValue: (r) => r.cycle_number,
      render: (r) => <span className="faint num">{r.cycle_number}</span> },
    { key: "time", header: "Time", width: "78px",
      render: (r) => <span className="faint num" style={{ fontSize: 11 }}>{fmtTime(r.timestamp)}</span> },
    { key: "asset", header: "Asset", sortable: true, sortValue: (r) => r.asset,
      render: (r) => (
        <div>
          <div style={{ fontWeight: 600 }}>{ASSET_NAME[r.asset] ?? r.asset}</div>
          <div className="faint" style={{ fontSize: 11 }}>{AGENT_LABEL[r.market_type]}</div>
        </div>
      ) },
    { key: "action", header: "Proposed", sortable: true, sortValue: (r) => r.action,
      render: (r) => <Badge tone={actionInfo(r.action).tone}>{actionInfo(r.action).label}</Badge> },
    { key: "conf", header: "Confidence", align: "right", sortable: true, sortValue: (r) => r.confidence,
      render: (r) => <span className="num">{(r.confidence * 100).toFixed(0)}%</span> },
    { key: "verdict", header: "Safety Check", sortable: true, sortValue: (r) => r.risk_verdict,
      render: (r) => <Badge tone={verdictInfo(r.risk_verdict).tone}>{verdictInfo(r.risk_verdict).label}</Badge> },
    { key: "money", header: "Money Assigned", align: "right", sortable: true, sortValue: (r) => r.final_allocation,
      render: (r) => <span className="num">{r.final_allocation > 0 ? fmtCurrency(r.final_allocation) : "—"}</span> },
    { key: "result", header: "Result", align: "right", sortable: true, sortValue: (r) => r.pnl,
      render: (r) =>
        r.outcome_status === "EVALUATED" ? (
          <span className={`num ${pnlTone(r.pnl)}`}>{r.pnl >= 0 ? "+" : ""}{fmtCurrency(r.pnl, 2)}</span>
        ) : r.executed ? <span className="faint">Monitoring</span> : <span className="faint">—</span> },
  ];

  const openRow = openId !== null ? decisions.find((d) => d.id === openId) ?? null : null;

  return (
    <div className="page">
      <PageHeader
        title="Decisions"
        description="Every decision the system makes passes through the same sequence of steps. Nothing is executed until each step has run."
      />

      {latest && focus ? (
        <Panel
          title="Decision in progress"
          sub={ASSET_NAME[focus.asset] ?? focus.asset}
          actions={
            <>
              {pinnedAsset && <button className="sm" onClick={() => setPinnedAsset(null)}>Follow latest</button>}
              <Badge tone={regimeInfo(focus.regime).tone}>{regimeInfo(focus.regime).label}</Badge>
            </>
          }
        >
          <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(0,1fr)", gap: 18 }} className="dec-grid">
            <PipelineFlow entry={focus} />
            <div>
              <StatRow cols={2}>
                <StatTile term={T.confidence} small value={`${(focus.proposal.confidence * 100).toFixed(0)}%`} />
                <StatTile term={T.expectedRisk} small value={focus.proposal.expected_risk.toFixed(2)} />
              </StatRow>
              <div style={{ height: 12 }} />
              <div className="callout">
                <div className="callout-label">
                  Reasoning — {focus.proposal.ai_provider_used === "groq" ? "written by the language model" : "generated by the rule engine"}
                </div>
                {humanize(focus.proposal.reasoning)}
              </div>
              <div style={{ height: 12 }} />
              <div className="callout-label" style={{ marginBottom: 5 }}>Supporting signals</div>
              <ul className="reasons">{focus.proposal.factors.map((f, i) => <li key={i}>{f}</li>)}</ul>
              <div style={{ height: 10 }} />
              <div className="callout-label" style={{ marginBottom: 5 }}>Risks considered</div>
              <ul className="reasons">{focus.proposal.risk_factors.map((f, i) => <li key={i}>{f}</li>)}</ul>
              <div style={{ height: 10 }} />
              <div className="kv">
                <span className="k">Approach used</span>
                <span className="v">{strategyLabel(focus.proposal.strategy_tag)}</span>
              </div>
              <div className="kv">
                <span className="k">Expected price move</span>
                <span className="v">{fmtPct(focus.proposal.expected_return_pct)}</span>
              </div>
            </div>
          </div>
        </Panel>
      ) : (
        <Panel><Empty title="No decision in progress">Start the simulation to watch a decision move through the pipeline.</Empty></Panel>
      )}

      <Panel
        title="Decision history"
        sub={`${rows.length} shown`}
        flush
        actions={
          <div className="btn-group">
            {(["ALL", "ACTED", "BLOCKED"] as Filter[]).map((f) => (
              <button key={f} className={`sm${filter === f ? " on" : ""}`} onClick={() => setFilter(f)}>
                {f === "ALL" ? "All" : f === "ACTED" ? "Traded" : "Changed or blocked"}
              </button>
            ))}
          </div>
        }
      >
        <DataTable
          columns={columns}
          rows={rows.slice(0, 100)}
          rowKey={(r) => String(r.id)}
          onRowClick={(r) => setOpenId(openId === r.id ? null : r.id)}
          selectedKey={openId !== null ? String(openId) : null}
          minWidth={900}
          emptyTitle="No decisions match this filter"
          emptyBody="Run the simulation to build up a decision history."
        />
      </Panel>

      {openRow && <HistoricDetail row={openRow} />}

      <style>{`@media (max-width: 1100px) { .dec-grid { grid-template-columns: 1fr !important; } }`}</style>
    </div>
  );
}

function HistoricDetail({ row }: { row: DecisionRow }) {
  const act = actionInfo(row.action);
  const verdict = verdictInfo(row.risk_verdict);
  const wasChanged = row.risk_verdict === "MODIFY" || row.final_allocation < row.proposed_allocation;

  return (
    <Panel title="Decision detail" sub={`Step ${row.cycle_number} · ${ASSET_NAME[row.asset] ?? row.asset}`}
      actions={<Badge tone={act.tone}>{act.label}</Badge>}>
      <StatRow cols={4}>
        <StatTile label="Agent" small value={<span style={{ fontSize: 13 }}>{AGENT_LABEL[row.market_type]}</span>} />
        <StatTile term={T.confidence} small value={`${(row.confidence * 100).toFixed(0)}%`} />
        <StatTile label="Safety Check" small value={<Badge tone={verdict.tone}>{verdict.label}</Badge>} />
        <StatTile term={T.moneyAssigned} small value={row.final_allocation > 0 ? fmtCurrency(row.final_allocation) : "None"} />
      </StatRow>

      <div style={{ height: 12 }} />
      <div className="callout">
        <div className="callout-label">Why the system decided this</div>
        {humanize(row.reasoning)}
      </div>

      {row.event_description && (
        <>
          <div style={{ height: 10 }} />
          <div className="kv"><span className="k">Market event at the time</span><span className="v">{row.event_description}</span></div>
        </>
      )}

      <div className="sep" />
      <div className="grid-2">
        <div>
          <div className="callout-label" style={{ marginBottom: 5 }}>Safety check outcome</div>
          <ul className="reasons">
            {row.risk_reasons.split("; ").filter(Boolean).map((r, i) => <li key={i}>{humanize(r)}</li>)}
          </ul>
          {wasChanged && (
            <div className="kv" style={{ marginTop: 6 }}>
              <span className="k">Amount changed</span>
              <span className="v">
                {fmtCurrency(row.proposed_allocation)} → {fmtCurrency(row.final_allocation)}
              </span>
            </div>
          )}
        </div>
        <div>
          <div className="callout-label" style={{ marginBottom: 5 }}>What happened next</div>
          {row.executed ? (
            <>
              <div className="kv"><span className="k">Executed at</span><span className="v">{fmtCurrency(row.execution_price, 2)}</span></div>
              <div className="kv"><span className="k">Units</span><span className="v">{row.execution_quantity.toFixed(3)}</span></div>
              <div className="kv"><span className="k">Trading fee</span><span className="v">{fmtCurrency(row.transaction_cost, 2)}</span></div>
              {row.outcome_status === "EVALUATED" ? (
                <>
                  <div className="kv"><span className="k">Expected move</span><span className="v">{fmtPct(row.expected_return_pct)}</span></div>
                  <div className="kv"><span className="k">Actual move</span><span className={`v ${pnlTone(row.actual_return_pct)}`}>{fmtPct(row.actual_return_pct)}</span></div>
                  <div className="kv"><span className="k">Result</span><span className={`v ${pnlTone(row.pnl)}`}>{row.pnl >= 0 ? "+" : ""}{fmtCurrency(row.pnl, 2)}</span></div>
                </>
              ) : (
                <div className="faint" style={{ fontSize: 12, marginTop: 6 }}>
                  Still being monitored — the system checks back a few steps later.
                </div>
              )}
            </>
          ) : (
            <div className="faint" style={{ fontSize: 12 }}>No trade was placed for this decision.</div>
          )}
        </div>
      </div>
    </Panel>
  );
}
